version: '3.7'

services:
  www:
    build: 
      context: .
      dockerfile: ./Docker/Dockerfile
    ports:
      - ${APACHE_PORT}:80
    volumes:
      - .:/var/www/html
    networks:
      - dev-server

  db:
    image: mariadb:${MARIADB_VERSION}
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: "Africa/Johannesburg"
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MARIADB_ALLOW_EMPTY_PASSWORD}
    command: --sql_mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION"
    networks:
      - dev-server

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${MY_ADMIN_PORT}:80
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: ""
      UPLOAD_LIMIT: "2048M"
    networks:
      - dev-server

volumes:
  db-volume:

networks:
  dev-server: